from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, Sequence


@dataclass(frozen=True)
class RetrievedChunk:
    document_id: str
    chunk_index: int
    content: str
    distance: float


@dataclass(frozen=True)
class ProcessedDocument:
    chunks: list[str]


class TenantRepository(Protocol):
    async def create(self, name: str): ...
    async def get(self, tenant_id: str): ...
    async def get_by_api_key(self, api_key: str): ...
    async def list(self, skip: int, limit: int) -> Sequence[object]: ...
    async def soft_delete(self, tenant_id: str) -> None: ...


class DocumentRepository(Protocol):
    async def create(self, tenant_id: str, filename: str, content_type: str, file_size: int): ...
    async def get(self, document_id: str, tenant_id: str): ...
    async def list(self, tenant_id: str, skip: int, limit: int) -> Sequence[object]: ...
    async def update_chunk_count(self, document_id: str, tenant_id: str, count: int) -> object: ...
    async def soft_delete(self, document_id: str, tenant_id: str) -> None: ...


class DocumentProcessor(Protocol):
    def process(self, content_type: str, content: bytes) -> ProcessedDocument: ...


class EmbeddingProvider(Protocol):
    async def embed(self, texts: list[str]) -> list[list[float]]: ...
    async def is_available(self) -> bool: ...


class LanguageModel(Protocol):
    async def answer(self, question: str, context: str) -> str: ...


class VectorStore(Protocol):
    def add(self, tenant_id: str, document_id: str, chunks: list[str], embeddings: list[list[float]]) -> int: ...
    def search(self, tenant_id: str, embedding: list[float], limit: int) -> list[RetrievedChunk]: ...
    def delete_document(self, tenant_id: str, document_id: str) -> int: ...
    def delete_tenant(self, tenant_id: str) -> int: ...
